# SPDX-License-Identifier: GPL-2.0-only

obj-y += soph_vo_sys_reg.o soph_mipipll_cfg.o soph_bmp.o soph_vo.o soph_crtc.o soph_bridge.o soph_connector.o drm_modes.o dw_hdmi.o
obj-$(CONFIG_DISPLAY_SOPH_HDMI) += soph_dw_hdmi.o


