#obj-y := utask/cv181x/cvi_usb.o
#obj-y += utask/cv181x/cps_cvi.o
#obj-y += utask/cv181x/cvi_udc_otg.o
#obj-y += utask/cv181x/cvi_udc_otg_xfer_dma.o
#obj-y += utask/cv181x/usb_tty.o


obj-y := utask/cv186x/cvi_usb.o
obj-y += utask/cv186x/cps_cvi.o
obj-y += utask/cv186x/core.o
obj-y += utask/cv186x/ep0.o
obj-y += utask/cv186x/udc-core.o
obj-y += utask/cv186x/gadget.o
obj-y += utask/cv186x/usb_tty.o
