#obj-y := utask/cv181x/cvi_usb.o
#obj-y += utask/cv181x/cps_cvi.o
#obj-y += utask/cv181x/cvi_udc_otg.o
#obj-y += utask/cv181x/cvi_udc_otg_xfer_dma.o
#obj-y += utask/cv181x/usb_tty.o


obj-y := utask/athena2/cvi_usb.o
obj-y += utask/athena2/cps_cvi.o
obj-y += utask/athena2/core.o
obj-y += utask/athena2/ep0.o
obj-y += utask/athena2/udc-core.o
obj-y += utask/athena2/gadget.o
obj-y += utask/athena2/usb_tty.o
